name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install Libraries
        run: |
          .\vcpkg\vcpkg install wxwidgets:x64-windows
          .\vcpkg\vcpkg install opencv4:x64-windows
          .\vcpkg\vcpkg install curl:x64-windows

      - name: Configure
        run: cmake -B build -S . "-DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: cmake --build build --config Release

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: OriginCam-Windows
          path: build/Release/*