name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install libs
        run: |
          .\vcpkg\vcpkg install wxwidgets:x64-windows
          .\vcpkg\vcpkg install opencv4:x64-windows
          .\vcpkg\vcpkg install curl:x64-windows

      - name: Configure
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=.\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release