name: Build Windows EXE

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11

      - name: Install Libraries
        run: |
          vcpkg install wxwidgets:x64-windows
          vcpkg install opencv4:x64-windows
          vcpkg install curl:x64-windows

      - name: Configure
        run: cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake

      - name: Build
        run: cmake --build build --config Release